### ISSUE TITLE
Softwareentwurf-Vertikalgradient/Tiefenbestimmung

### ISSUE THREAD

**Issue by JulianMilde** [JulianMilde/Projekt_Softwareentwicklung2024#1]
Die UML-Diagramme zur Heatmap habe ich inzwischen zum Wiki hinzugefügt.
Ich habe VisualParadigm (https://online.visual-paradigm.com/drive/#diagramlist:proj=0&dashboard). verwendet und dann über Share einen Link erstellt (Registrierung mit Email nötig!), den ich in das Wiki eingefügt habe.
Du müsstes nun noch die UML-Diagramme (Use-Case-, Aktivitäts-, Klassendiagramm) für den Vertikalgradienten bzw. die Tiefenbestimmung erstellen.
Die Website ist vielleicht ganz hilfreich, wenn dir die Syntax nicht ganz klar ist https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/.

**Deadline:** 07-07-2024

**Comment by TomArzig** [comment]
Die UML-Diagramme für Vertikalgradient bzw. Tiefenbestimmung habe ich erstellt und im Wiki eingefügt.
