### ISSUE TITLE
Isolinienkarte

### ISSUE THREAD

**Issue by JulianMilde** [JulianMilde/Projekt_Softwareentwicklung2024#2]
Erstellung der Isolinienkarte (Finetuning des Programmes dann zwischen **22.07. und 24.07**)

1. Erstellung der Farbkarte (nach Interpolation und Einlesen der CSV-Datei)
2. Erstellung der Isolinien
3. Dateipfad soll übergeben und die Karte automatisch gespeichert werden können
4. Zur Überprüfung des Programmes auf GitHub laden

**Deadline 17.07.2024**

**Comment by JulianMilde** [comment]
**Deadline wurde verlängert (19.07.2024)**; Grund: Probleme beim Klonen des Repository.

**Comment by TomArzig** [comment]
Ich würde sagen, wir können dieses Issue und Issue #3 Vertikalgradient schließen, der Code ist für beide fertig und hochgeladen, nur die Tests und die Dokumentation fehlen noch bzw. funktionieren noch nicht ganz. Was meinst du? @JulianMilde

**Comment by JulianMilde** [comment]
Ja können wir machen. Ursprünglich wollte ich noch warten, bis alle Tests erfolgreich waren, aber da dies jetzt ziemlich lang dauert können wir das schon mal schließen (und die Tests sind dann Teil des Issues "Dokumentation/Softwareentwurf).

**Comment by TomArzig** [comment]
Ich habe mir deinen Code auch mal kurz angeschaut, sieht auf den ersten Blick sehr gut aus. Dann kannst du dein Issue auch schließen.

**Comment by JulianMilde** [comment]
Danke
