### ISSUE TITLE
Vertikalgradient

### ISSUE THREAD

**Issue by JulianMilde** [JulianMilde/Projekt_Softwareentwicklung2024#3]
Erstellung des Vertikalgradienten und Bestimmung der Tiefe des Objektes (Finetuning **22.07. bis 24.07.**)

0. Erstellung einer CSV-Datei (mit X, B(z1), B(z2))
1. Erstellung des Diagramms (Vertikalgradient)
2. Berechnung der Tiefe
3. Kurzer Auswertungssatz
(4. Eventuelle Verknüpfung mit der Isolinienkarte  [abhängig von der Zeit])

**Deadline 17.07.2024**

**Comment by JulianMilde** [comment]
**Deadline wurde verlängert (19.07.2024)**; Grund: Probleme beim Klonen des Repository.

**Comment by TomArzig** [comment]
**Deadline wurde verlängert (20.07.2024)**; Grund: Probleme beim Commit aufgetreten

**Comment by TomArzig** [comment]
Code für den Vertikalgradienten ist fertig geschrieben (bis auf eventuelle Verknüpfung mit Isolinienkarte), ich würde mit dem Hochladen noch warten bis ich die automatischen Tests und die Dokumentation fertig implementiert habe

**Comment by JulianMilde** [comment]
Ich habe mir den Code mal angeschaut/überflogen. Das sollte so passen, du kannst das Issue also schließen. :)
