### ISSUE TITLE
Dokumentation/Softwareentwurf

### ISSUE THREAD

**Issue by JulianMilde** [JulianMilde/Projekt_Softwareentwicklung2024#4]
Die Aspekte der Dokumentation (Tutorial, Beispielcode, Erläuterungen der API), sowie die Aspekte des Softwareentwurfs (Dokumentation des methodischen Vorgehens und integrierte Tests) müssen noch umgesetzt werden.

**Softwareentwurf**
- [x] Dokumentation des methodischen Vorgehens
- [x]  integrierte Tests

**Dokumentation**
- [x] Erläuterungen der API
- [x] Beispielcode
- [x] Tutorial

**Comment by JulianMilde** [comment]
Ob das automatische Testen und Dokumentieren funktioniert kann überprüft werden, sobald das Problem mit dem Klonen des Repos. behoben wurde (ein Workflow wurde schon erstellt).

**Comment by JulianMilde** [comment]
Ich weiß nicht genau, was er mit Beispielcodes meint, deshalb würde ich das auslassen (wir haben nicht wirklich Beispielcodes).
Das Tutorial erstelle ich morgen Vormittag und füge den Link in die ReadMe file ein. Die Erläuterung der API müsste in der Dokumentation im Wiki dabei sein, diese kann aber noch etwas konkreter werden und auch der Workflow müsste noch erklärt werden.

**Comment by TomArzig** [comment]
Alles klar. Das würde ich dann noch übernehmen.

**Comment by TomArzig** [comment]
Ich habe jetzt Bildschirmaufnahmen davon gemacht, wie ich das Vertikalgradientenprogramm ausführe und teste (lokal), damit du morgen noch das Tutorial erstellen kannst. Die würde ich dir gleich mal über Whatsapp schicken

**Comment by JulianMilde** [comment]
Vielen Dank, die habe ich erhalten!

**Comment by JulianMilde** [comment]
Ich habe ein (vorläufiges) Tutorial erstellt. Schau einfach mal in der ReadMe file vorbei ;)

**Comment by JulianMilde** [comment]
Ich habe noch schnell etwas zur API hinzugefügt und schließe damit jetzt das Issue  (da alle Punkte abgearbeitet sind).
